import { snapshot } from "../wealth-model"
import { facilityInterest } from "../finance-math"
import type { StressScenario } from "@/lib/types"
import { cheungRaw, raviRaw } from "./triggers"

const money = (value: number) => `USD ${Math.abs(value / 1_000_000).toFixed(2)}m`

export function raviStressScenarios(): StressScenario[] {
  const facility = snapshot.facilities.find(f => f.id === "CF-0001")!
  const currentInterest = facilityInterest(facility)
  const shockedInterest = facilityInterest(facility, 12, 100)
  const sixMonthInterest = facilityInterest(facility, 6).amount
  const incrementalInterest = shockedInterest.amount - currentInterest.amount
  const trustNeed = snapshot.needs.find(n => n.id === "CN-003")!.usd
  const founderLoss = raviRaw.privateCompany * 0.2
  const advisoryTechLoss = raviRaw.informationTechnology * 0.2
  const loss = founderLoss + advisoryTechLoss
  const stressedCollateral = raviRaw.collateralValue - raviRaw.collateralTechValue * 0.2
  const stressedLtv = (raviRaw.drawn / stressedCollateral) * 100
  return [
    { id: "ravi-tech", label: "Technology −20%", impactLabel: `−${money(loss)}`, portfolioImpactPct: (loss / raviRaw.totalAum) * 100, result: `Stressed wealth USD ${((raviRaw.totalAum - loss) / 1_000_000).toFixed(2)}m · collateral LTV ${stressedLtv.toFixed(1)}%`, detail: "Applies the same shock to founder stock and disclosed technology exposure; no diversification benefit is assumed.", components: ["Founder stock −USD 6.38m", "Advisory technology −USD 1.89m", "Trigger LTV exceeded by 8.0pp"], drivers: [{ label: "Founder stock", value: -13.67 }, { label: "Advisory technology", value: -4.04 }], comparison: { current: "USD 46.70m · LTV 73.71%", stressed: `USD ${((raviRaw.totalAum - loss) / 1_000_000).toFixed(2)}m · LTV ${stressedLtv.toFixed(1)}%`, afterAction: "LTV restored to 75%", afterActionNote: "Repay USD 0.63m or add USD 0.84m eligible lending value" }, decision: { title: "Protect the bridge without forcing a technology sale", summary: "Use a pre-agreed collateral cure before the facility controls the timing.", rebalance: [{ action: "Add diversified eligible collateral", amount: "USD 0.84m lending value", rationale: "Restores 75% LTV without selling the listed technology sleeve." }, { action: "Alternative debt cure", amount: "Repay USD 0.63m", rationale: "Reduces utilisation immediately if collateral cannot be added." }], reasoning: ["Technology affects both wealth and borrowing capacity.", "The sale is not liquidity until cash settles.", "A cure agreed now gives the RM time to act."], taxOpportunity: { title: "Sequence the liquidity event", detail: "Review cost basis, tax reserves, and the order of post-sale debt repayment before the secondary sale closes.", guardrail: "Singapore tax treatment and sale documents require specialist confirmation." } } },
    { id: "ravi-delay", label: "Sale delayed 6 months", impactLabel: `−${money(sixMonthInterest)} carry`, portfolioImpactPct: sixMonthInterest / raviRaw.totalAum * 100, result: "Trust funding remains unfunded; USD 6.5m borrowing stays outstanding", detail: "Uses the current 6.15% facility rate for six months. Tax, fees, and rate changes are excluded.", components: ["Facility carry ≈ USD 200k", "USD 2.0m trust need remains", "Liquidity event moves beyond Q4 2026"], drivers: [{ label: "Facility carry", value: -0.43 }], comparison: { current: "Q4 2026 expected sale", stressed: `Q2 2027 · ${money(sixMonthInterest)} carry`, afterAction: "Agree a funded bridge", afterActionNote: "Confirm cash for trust funding and interest; no funding assumed" }, decision: { title: "Fund the delay before it happens", summary: "Treat the banker indication as uncertain and set a 12-month liquidity runway.", rebalance: [{ action: "Reserve interest and trust funding", amount: money(trustNeed + sixMonthInterest), rationale: "Covers the likely trust need and six months of facility carry." }, { action: "Stop additional facility draws", amount: "USD 0 new debt", rationale: "Preserves the remaining collateral buffer." }], reasoning: ["Completion date and valuation can change.", "The trust need arrives before cash settlement is certain.", "Pre-funding avoids a forced sale during volatility."], taxOpportunity: { title: "Build the sale proceeds waterfall", detail: "Model debt repayment, tax reserve, trust funding, and diversification before proceeds arrive.", guardrail: "Use verified sale terms and tax advice; do not count gross proceeds as spendable cash." } } },
    { id: "ravi-rates", label: "Facility rate +100bp", impactLabel: `−${money(incrementalInterest)} / year`, portfolioImpactPct: incrementalInterest / raviRaw.totalAum * 100, result: "Annual interest cost rises by USD 65k", detail: "Applies 100bp to the current USD 6.5m drawn balance with no change in utilization.", components: ["Current draw USD 6.5m", "Incremental annual interest USD 65k", "No market-value shock included"], drivers: [{ label: "Interest cost", value: -0.14 }], comparison: { current: `${currentInterest.rate.toFixed(2)}% · ${money(currentInterest.amount)} interest`, stressed: `${shockedInterest.rate.toFixed(2)}% · ${money(shockedInterest.amount)} interest`, afterAction: "Lower interest burden", afterActionNote: "Repay debt first when sale proceeds settle" }, decision: { title: "Make debt repayment the first use of proceeds", summary: "The facility is useful as a bridge, but it should not become permanent leverage.", rebalance: [{ action: "Post-sale debt repayment", amount: "USD 6.50m", rationale: "Removes rate and collateral risk before new allocations." }], reasoning: ["Rate risk is certain while sale timing is not.", "Repayment increases future investment flexibility.", "New risk should follow, not precede, debt reduction."], taxOpportunity: { title: "Compare debt cost with taxable distributions", detail: "Review whether income-producing assets create avoidable taxable cash flow while high-cost debt remains.", guardrail: "Confirm tax character and early repayment terms before action." } } },
  ]
}

export function cheungStressScenarios(): StressScenario[] {
  const durationLoss = 2_750_000
  return [
    { id: "cheung-rates", label: "Rates +200bp", impactLabel: `−${money(durationLoss)}`, portfolioImpactPct: (durationLoss / cheungRaw.totalAum) * 100, result: `Stressed wealth USD ${((cheungRaw.totalAum - durationLoss) / 1_000_000).toFixed(2)}m`, detail: "Uses disclosed sleeve shocks: long Treasury −18%, credit −8%, perpetuals −12%, infrastructure debt −5%, and rate-sensitive equities −10%.", components: ["Estimated total loss USD 2.75m", "2045 Treasury is the largest driver", "Cash reserve is unchanged"], drivers: [{ label: "2045 Treasury", value: -3.74 }, { label: "Credit funds", value: -2.54 }, { label: "Perpetuals", value: -1.69 }, { label: "Rate-sensitive equity", value: -1.03 }, { label: "Other equity", value: -0.59 }, { label: "Infrastructure debt", value: -0.21 }], comparison: { current: "USD 28.03m", stressed: "USD 25.28m", afterAction: "Lower duration sensitivity", afterActionNote: "Stage USD 1.50m from the 2045 bond into a short ladder" }, decision: { title: "Reduce duration in stages", summary: "Do not force a full loss realisation. Build the spending runway while reducing the largest rate driver.", rebalance: [{ action: "Shorten the 2045 Treasury", amount: "USD 1.50m staged", rationale: "Reduces duration and funds part of the spending reserve." }, { action: "Add short-duration income", amount: "USD 1.00m", rationale: "Matches near-term withdrawals with more stable cash flows." }], reasoning: ["The long bond is 20.8% of AUM.", "Medical withdrawals are already above plan.", "A staged move respects the client’s loss aversion."], taxOpportunity: { title: "Pair losses with appreciated shipping exposure", detail: "Review whether a partial shipping gain and a measured bond loss can be realised in the same tax period.", guardrail: "Confirm Hong Kong tax treatment, transaction costs, and suitability before trading." } } },
    { id: "cheung-medical", label: "Medical spend +25%", impactLabel: "USD 2.85m cash gap", portfolioImpactPct: 10.16, result: "Three-year reserve target rises to USD 4.80m", detail: "Raises the current USD 1.28m annual draw to USD 1.60m and compares it with current cash.", components: ["Annual draw USD 1.60m", "Three-year need USD 4.80m", "Current cash USD 1.95m"], drivers: [{ label: "Reserve shortfall", value: -10.16 }], comparison: { current: "USD 1.28m annual spend", stressed: "USD 1.60m annual spend", afterAction: "USD 4.80m runway", afterActionNote: "Three years held in cash and short-duration assets" }, decision: { title: "Make medical liquidity explicit", summary: "Separate the spending reserve from the long-term income portfolio.", rebalance: [{ action: "Build a three-year reserve", amount: "USD 4.80m target", rationale: "Removes the need to sell long bonds to fund care." }], reasoning: ["The annual draw is already 16.4% above the original plan.", "Current cash funds about 15 months at the stressed rate.", "A reserve makes the long-term sleeve easier to hold."], taxOpportunity: { title: "Choose reserve funding lots deliberately", detail: "Compare high-cost lots, loss positions, coupons, and appreciated shipping exposure before funding the reserve.", guardrail: "Confirm local tax treatment and product settlement dates." } } },
    { id: "cheung-shipping", label: "Shipping holding −15%", impactLabel: "−USD 0.25m", portfolioImpactPct: 0.87, result: "Recent shipping gains would partly reverse", detail: "Illustrative shock to Pacific Orient only. This is a sensitivity, not a forecast of shipping conditions.", components: ["Single-position shock", "Estimated loss USD 245k", "No offset from bonds assumed"], drivers: [{ label: "Pacific Orient", value: -0.87 }], comparison: { current: "Recent gain retained", stressed: "USD 0.25m value loss", afterAction: "Part of gain secured", afterActionNote: "Use a partial trim to fund medical reserves" }, decision: { title: "Use the gain as a funding window", summary: "A partial trim can improve liquidity without abandoning the holding.", rebalance: [{ action: "Trim appreciated shipping exposure", amount: "USD 0.50m review", rationale: "Locks part of the gain and reduces familiarity bias." }], reasoning: ["The source of wealth is already linked to shipping.", "The reserve has a current shortfall.", "Waiting exposes the recent gain to reversal."], taxOpportunity: { title: "Review gain and loss pairing", detail: "Assess the shipping gain beside long-duration bond losses when selecting lots.", guardrail: "Tax rules and costs require specialist confirmation." } } },
  ]
}
