"use client"

import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, Check, FileCheck2, ListFilter, LockKeyhole, RotateCcw, Target } from 'lucide-react'
import { Input } from './ui/input'
import { FactCheckBubble } from './fact-check-bubble'
import { recommendationEvidence } from '@/lib/recommendation-evidence'
import { NativeSelect, NativeSelectOption } from './ui/native-select'
import { Slider } from './ui/slider'
import { Label } from './ui/label'
import { Textarea } from './ui/textarea'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from './ui/table'
import { appendDecision } from '@/lib/ledger'
import { draftNumber } from '@/lib/input-validation'
import { exactMoney, money, snapshot, type ValueRules, type Wealth } from '@/lib/wealth-model'
import { defaultPriorities, defaultReserveCurrency, defaultReserveGoal, defaultTargetAccount, goalKeys, goalLabels, recommendationAllocation, recommendationVersion, recommendPortfolios, type GoalKey, type PortfolioRecommendation, type Priorities } from '@/lib/recommendations'

type Props = { wealth: Wealth; annualNeed: number; incomeMultiplier: number; lossLimit: number; rules: ValueRules; requestedReturn: string; requestedYield: string; goalErrors: string[]; onOpenGoals: () => void; onOpenAccounts: () => void }
const signed = (value: number) => `${value > 0 ? '+' : value < 0 ? '−' : ''}${money(Math.abs(value))}`
const points = (value: number) => Math.abs(value) < 1e-8 ? '0.00' : `${value > 0 ? '+' : '−'}${Math.abs(value) < .005 ? '<0.01' : Math.abs(value).toFixed(2)}`
const colors = { liquidity: '#001489', income: '#007770', preservation: '#717899', growth: '#AFAA7D', diversification: '#141E55', change: '#D0D2DD' }

export function PortfolioRecommendations({ wealth, annualNeed, incomeMultiplier, lossLimit, rules, requestedReturn, requestedYield, goalErrors = [], onOpenGoals, onOpenAccounts }: Props) {
  const [priorities, setPriorities] = useState<Priorities>(() => defaultPriorities(wealth))
  const [edited, setEdited] = useState(false)
  const [accountId, setAccountId] = useState(() => defaultTargetAccount(wealth))
  const [reserveOverride, setReserveOverride] = useState('')
  const [reserveCurrency, setReserveCurrency] = useState(() => defaultReserveCurrency(wealth))
  const [horizon, setHorizon] = useState(String(wealth.client.horizon))
  const [maxTransitionPct, setMaxTransitionPct] = useState(100)
  const [selectedId, setSelectedId] = useState('')
  const [feedbackFocus, setFeedbackFocus] = useState<GoalKey>('income')
  const [outcome, setOutcome] = useState('Shortlist for RM review')
  const [note, setNote] = useState('')
  const [saved, setSaved] = useState('')
  const reserveGoal = reserveOverride === '' ? defaultReserveGoal(wealth, annualNeed) : draftNumber(reserveOverride)
  const report = useMemo(() => recommendPortfolios(wealth, { accountId, priorities, reserveGoal, reserveCurrency, annualNeed, targetYield: requestedYield === '' ? null : draftNumber(requestedYield), lossLimit, horizon: draftNumber(horizon), incomeMultiplier, rules, maxTransitionPct }), [wealth, accountId, priorities, reserveGoal, reserveCurrency, annualNeed, requestedYield, lossLimit, horizon, incomeMultiplier, rules, maxTransitionPct])
  const inputErrors = [...new Set([...goalErrors, ...report.inputErrors])]
  const selected = report.candidates.find(c => c.id === selectedId) || report.top || report.candidates[0]
  const unfunded = selected.id !== 'retain' && selected.amount <= .01
  const target = wealth.accounts.find(a => a.id === accountId)
  const rows = recommendationAllocation(wealth, report.input, selected)
  const other = report.top?.id === selected.id ? report.eligible[1] || report.blocked[0] : report.top
  const activeValues = Object.entries(rules).filter(([, active]) => active).map(([key]) => key)
  const priorityNames = goalKeys.filter(k => priorities[k] > 0).sort((a, b) => priorities[b] - priorities[a]).slice(0, 2).map(k => goalLabels[k].toLowerCase())
  useEffect(() => { setSaved('') }, [report, selected.id, requestedReturn])
  useEffect(() => { setNote(''); setOutcome('Shortlist for RM review') }, [selected.id, accountId])

  function changePriority(key: GoalKey, value: number) { setPriorities({ ...priorities, [key]: value }); setEdited(true); setSelectedId(''); setSaved('') }
  function applyFeedback() {
    setPriorities(Object.fromEntries(goalKeys.map(k => [k, k === feedbackFocus ? 5 : Math.min(priorities[k], 2)])) as Priorities)
    setEdited(true); setSelectedId(''); setSaved('Priorities updated in this simulation. Source preferences and hard gates stay in force.')
  }
  function saveRationale() {
    if (inputErrors.length) { setSaved('Correct the inputs before saving a recommendation review.'); return }
    if (selected.status === 'blocked' && outcome === 'Shortlist for RM review') { setSaved('This option fails a gate. Record a change request or rejection instead of shortlisting it.'); return }
    if (note.trim().length < 8) { setSaved('Add a short RM reason before saving.'); return }
    try {
      appendDecision({ insightId: 'goal-recommendation-' + wealth.client.id, client: wealth.client.name, insightTitle: `${outcome} · ${selected.name}`, decision: outcome === 'Reject option' ? 'Ignore' : 'Modify', note: JSON.stringify({ status: 'PRE-ADVICE SIMULATION — NOT CLIENT OR TRADE APPROVAL', engine: recommendationVersion, snapshot: snapshot.asOf, inputs: report.input, externalExamples: wealth.external, candidate: selected.id, rank: selected.rank, score: selected.score, scoreUnavailableReason: selected.scoreUnavailableReason, baselineScore: report.baseline.score, scoreChange: selected.scoreChange, effectBasis: unfunded ? 'Model not applied' : selected.id === 'retain' ? 'Current portfolio' : 'Modelled transition', allocation: unfunded ? null : rows, transitionPct: selected.transitionPct, amountUSD: selected.amount, gateResults: selected.gates, scoreBreakdown: selected.scoreParts, incomeAfterInterest: unfunded ? null : [selected.metrics.income.netLow, selected.metrics.income.netHigh], worstLossPct: unfunded ? null : selected.metrics.worstLoss, outcome, rmReason: note.trim(), evidence: report.evidence }) })
      setSaved('RM reason saved to this browser’s decision ledger. No trade, client message or approval was sent.')
    } catch { setSaved('This browser could not save the review. Keep the note and check browser storage access.') }
  }

  return <div className="recommendations">
    <div className="rec-heading"><div><p className="wealth-kicker">Before client advice</p><h3>Recommendations that start with the client</h3><p>Match goals to the whole wealth model, then explain the choice to the RM.</p></div><span className="wealth-tag"><Target size={15} />Goal matching · simulated</span></div>
    {inputErrors.length > 0 ? <div className="wealth-warning" role="alert"><strong>Check inputs before comparing portfolios</strong><ul>{inputErrors.map(error => <li key={error}>{error}</li>)}</ul><p>Scores, rankings and proposed effects are paused. Invalid amounts cannot remove a client constraint.</p></div> : <><div className={report.top ? 'rec-verdict' : 'rec-verdict rec-verdict-blocked'} aria-live="polite"><div className="rec-verdict-icon">{report.top ? <ListFilter size={25} /> : <LockKeyhole size={25} />}</div><div><p className="rec-overline">{report.top ? 'First option for RM review' : 'No portfolio clears the current gates'}</p><h3>{report.top ? report.top.name : 'Resolve the constraint before giving advice'}</h3><p>{report.nextAction}</p></div>{report.top && report.top.score !== null && <div className="rec-score-large"><strong>{report.top.score.toFixed(2)}<small>/100</small></strong><span>Goal fit · simulated</span></div>}</div>
    <div className="rec-context-strip"><span><strong>{report.eligible.length}</strong> options for review</span><span><strong>{report.blocked.length}</strong> blocked model families</span><span><strong>{money(report.eligibleAmount)}</strong> can be reshaped in this model</span><button onClick={onOpenAccounts}>Review wealth coverage <ArrowRight size={14} /></button></div></>}

    <div className="rec-layout">
      <aside className="rec-controls" aria-label="Recommendation inputs">
        <div className="rec-control-title"><Target size={18} /><h4>What matters most?</h4></div>
        <p className="wealth-small">{edited ? 'RM-adjusted draft priorities.' : 'Draft priorities inferred from source objectives and notes.'} Confirm with the client. Scores measure goal fit, not model accuracy, expected returns or suitability probability.</p>
        {goalKeys.map(key => <div className="rec-priority" key={key}><div><Label id={`rec-priority-${key}`}>{goalLabels[key]}</Label><span>{priorities[key]}/5</span></div><Slider aria-labelledby={`rec-priority-${key}`} value={[priorities[key]]} min={0} max={5} step={1} onValueChange={value => changePriority(key, value[0])} /></div>)}
        <button className="wealth-text-button" onClick={() => { setPriorities(defaultPriorities(wealth)); setEdited(false); setSelectedId(''); setSaved('') }}><RotateCcw size={14} />Reset source priorities</button>
        <div className="rec-control-divider" />
        <div className="rec-field"><Label htmlFor="rec-target">Account to reshape</Label><NativeSelect id="rec-target" value={accountId} onChange={e => { setAccountId(e.target.value); setSelectedId('') }}>{wealth.accounts.map(a => <NativeSelectOption key={a.id} value={a.id} disabled={a.external}>{a.name}{a.external ? ' · reference only' : ''}</NativeSelectOption>)}</NativeSelect></div>
        <div className="rec-field"><Label htmlFor="rec-reserve">Reserve goal · USD equivalent</Label><Input id="rec-reserve" aria-invalid={reserveOverride !== "" && (!Number.isFinite(reserveGoal) || reserveGoal < 0 || reserveGoal > 1e10)} type="number" min="0" max="10000000000" step="1000" value={reserveOverride} placeholder={String(Math.round(defaultReserveGoal(wealth, annualNeed)))} onChange={e => { setReserveOverride(e.target.value); setSelectedId('') }} /><span className="wealth-small">{reserveOverride === '' ? 'Draft default: ' : 'RM-entered: '}{Number.isFinite(reserveGoal) && reserveGoal >= 0 && reserveGoal <= 1e10 ? exactMoney(reserveGoal) : 'Invalid amount'}. Default = two years of entered annual need + likely/confirmed one-offs starting within 18 months. Check dates and mixed-currency needs.</span></div>
        <div className="rec-field"><Label htmlFor="rec-currency">Currency of this reserve</Label><NativeSelect id="rec-currency" value={reserveCurrency} onChange={e => { setReserveCurrency(e.target.value); setSelectedId('') }}>{Object.keys(snapshot.fx).map(c => <NativeSelectOption key={c}>{c}</NativeSelectOption>)}</NativeSelect></div>
        <div className="rec-field"><Label htmlFor="rec-horizon">Investment horizon · years</Label><Input id="rec-horizon" aria-invalid={!Number.isFinite(draftNumber(horizon)) || Number(horizon) < 0 || Number(horizon) > 100} type="number" min="0" max="100" step="0.5" value={horizon} onChange={e => { setHorizon(e.target.value); setSelectedId('') }} /></div>
        <div className="rec-priority"><div><Label id="rec-transition">Maximum eligible sleeve to reshape</Label><span>{maxTransitionPct}%</span></div><Slider aria-labelledby="rec-transition" value={[maxTransitionPct]} min={0} max={100} step={5} onValueChange={v => { setMaxTransitionPct(v[0]); setSelectedId('') }} /></div>
        <p className="wealth-small">The search can choose a smaller change. Custody, pledged, non-daily and protected loss positions stay fixed. No new loan or expected sale proceeds are created.</p>
        <div className="rec-fixed-inputs"><strong>Linked to Goals & values</strong><span>Annual need: {money(annualNeed)}</span><span>Requested gross yield: {requestedYield === '' ? 'Not agreed' : requestedYield + '%'}</span><span>Draft loss limit: {lossLimit}%</span><span>Income assumptions: {Math.round(incomeMultiplier * 100)}%</span><span>Values: {activeValues.length ? activeValues.join(', ') : 'Not confirmed'}</span><button className="wealth-text-button" onClick={onOpenGoals}>Edit goals & exclusions <ArrowRight size={14} /></button></div>
        {report.constraints.noListedSales && <p className="wealth-warning"><strong>Ravi’s no-listed-sales preference is fixed.</strong> Source: N-003, 3 Feb 2026. No new draw is assumed. N-004, 11 Jun, adds the collateral concern.</p>}
        {report.constraints.noLossSales && <p className="wealth-warning"><strong>Cheung’s no-loss-sales preference is fixed.</strong> Loss positions and positions without cost basis remain unchanged, including cash with a source-currency loss. Source: N-016, 16 Jul 2026.</p>}
      </aside>

      <div className="rec-results">{inputErrors.length ? <div className="wealth-note"><strong>Comparison paused</strong><p>Correct the inputs or update Goals & values to resume.</p><button className="wealth-text-button" onClick={onOpenGoals}>Review goal inputs <ArrowRight size={14} /></button></div> : <>
        <div className="wealth-section-head"><div><h3>Compare the options</h3><p>Five standard mixes, one goal-funded mix, plus the current portfolio. Select an option to inspect it.</p></div></div>
        <div className="wealth-note rec-baseline"><strong>Current portfolio goal fit: {report.baseline.score === null ? 'Not scored' : `${report.baseline.score.toFixed(2)}/100`}</strong><p>Each scored option is compared with this baseline using the same goals and wealth inputs.</p>{report.unscored.length > 0 && <p>{report.unscored.length} {report.unscored.length === 1 ? 'option has' : 'options have'} no score. A model with no funded change cannot inherit the current portfolio's score. Each card explains the missing input or restriction.</p>}</div>
        <div className="rec-candidates">{report.candidates.map(candidate => {
          const notApplied = candidate.id !== 'retain' && candidate.amount <= .01
          return <button key={candidate.id} onClick={() => { setSelectedId(candidate.id); setSaved('') }} aria-pressed={selected.id === candidate.id} className={`rec-candidate ${selected.id === candidate.id ? 'is-selected' : ''} ${candidate.status === 'blocked' ? 'is-blocked' : ''}`}>
            <div className="rec-candidate-top"><span className={candidate.status === 'review' ? 'wealth-tag wealth-tag-ok' : 'wealth-tag wealth-tag-alert'}>{candidate.rank ? `Rank ${candidate.rank} · RM review` : `${candidate.blocks.length} gates failed`}</span><span className="rec-card-score">{candidate.score === null ? <span className="rec-score-unavailable">Not scored</span> : <>{candidate.score.toFixed(2)}<small>/100</small><span className="rec-score-label">{candidate.id === 'retain' ? 'Current goal fit' : candidate.status === 'blocked' ? 'Diagnostic goal fit' : 'Goal fit'}</span></>}</span></div>
            <strong>{candidate.name}</strong><p>{candidate.purpose}</p>
            {candidate.scoreChange !== null && <span className="rec-score-change">{candidate.id === 'retain' ? 'Baseline for comparison' : `${points(candidate.scoreChange)} points vs current`}</span>}
            <div className="rec-card-facts"><span>{notApplied ? 'Change: not modelled' : `Change: ${money(candidate.amount)}`}</span><span>{notApplied ? 'Stress: not modelled' : `Worst test: −${candidate.metrics.worstLoss.toFixed(1)}%`}</span></div>
            <small>{candidate.scoreUnavailableReason || (candidate.blocks.length ? candidate.blocks[0].label + ': ' + candidate.blocks[0].reason : `${candidate.transitionPct.toFixed(1)}% of the eligible sleeve · conditional on RM checks`)}</small>
          </button>
        })}</div>
        <p className="wealth-small">Only options that pass every gate are ranked. A funded option that fails another gate can have a diagnostic score, but cannot be shortlisted. Scores use full precision; two decimals are shown. Genuine ties are possible. Changing goals or wealth inputs recalculates the comparison.</p>

        <section className="rec-explanation" aria-label="Recommendation reasoning">
          <div className="wealth-section-head"><div><p className="wealth-kicker">Why this option?</p><h3>{selected.name}</h3>{!inputErrors.length && <FactCheckBubble title="recommendation goal-fit score" derive={() => recommendationEvidence(wealth, report.input, selected.id)} revision={JSON.stringify([report.input, selected.id, wealth.external])} />}</div><span className={selected.status === 'review' ? 'wealth-tag wealth-tag-ok' : 'wealth-tag wealth-tag-alert'}>{selected.status === 'review' ? 'Conditional RM review' : 'Not ready for recommendation'}</span></div>
          <p className="rec-match-statement">The current priorities are <strong>{priorityNames.length ? priorityNames.join(' and ') : 'not set'}</strong>. {selected.score === null ? 'This option has no goal-fit score. Resolve the restriction or missing goal below.' : selected.status === 'review' ? `This option passes the model gates and scores ${selected.score.toFixed(2)}/100.` : 'This option fails at least one mandatory gate. Its diagnostic goal fit does not clear that gate.'}</p>
          <ol className="rec-reasons">{selected.reasons.map((reason, index) => <li key={reason}><span>{index + 1}</span><p>{reason}</p></li>)}</ol>
          {selected.score !== null ? <>
            <div className="rec-score-track" aria-hidden="true">{selected.scoreParts.map(part => <span key={part.key} style={{ width: `${part.points}%`, background: colors[part.key] }} />)}</div>
            <details className="wealth-detail"><summary>Score breakdown · {selected.score.toFixed(2)}/100{selected.id !== 'retain' && selected.scoreChange !== null ? ` · ${points(selected.scoreChange)} points vs current` : ''}</summary><Table className="wealth-table"><TableHeader><TableRow><TableHead>Goal</TableHead><TableHead>Weight</TableHead><TableHead>Current points</TableHead><TableHead>Option points</TableHead><TableHead>Change</TableHead></TableRow></TableHeader><TableBody>{selected.scoreParts.map(part => {
              const baseline = report.baseline.scoreParts.find(p => p.key === part.key)
              return <TableRow key={part.key}><TableCell>{part.label}<small>{part.reason}</small></TableCell><TableCell>{part.weight.toFixed(1)}%</TableCell><TableCell>{baseline ? baseline.points.toFixed(2) : 'Not scored'}</TableCell><TableCell>{part.points.toFixed(2)}<small>Fit: {part.score.toFixed(2)}/100</small></TableCell><TableCell>{baseline ? points(part.points - baseline.points) : 'Not scored'}</TableCell></TableRow>
            })}</TableBody></Table><p>Active goal priorities split 90 points; avoiding unnecessary changes has 10 points. Points = weight × fit / 100. Cash and income goals without numeric targets are excluded. Loss fit is zero when the worst tested loss reaches or exceeds the draft limit; fully funded cash goals reach 100. Different portfolios can therefore have equal contributions. Inspect each goal and stress result. These are simulation scores; predictive accuracy has not been measured.</p></details>
          </> : <div className="wealth-note"><strong>No score or score change is available.</strong><p>{unfunded ? 'The model mix was not applied. The current portfolio is the only measured result.' : 'Set at least one usable goal to measure portfolio fit.'}</p>{unfunded && <button className="wealth-text-button" onClick={() => { setSelectedId('retain'); setSaved('') }}>Inspect current portfolio <ArrowRight size={14} /></button>}</div>}
          {other && <div className="rec-alternative"><h4>Why {selected.name} versus {other.name}?</h4><p>{comparisonReason(selected, other)}</p></div>}
        </section>

        {!unfunded && <section className="wealth-card"><h3>{selected.id === 'retain' ? 'Current portfolio and risk baseline' : 'The modelled portfolio and the whole-client effect'}</h3><p><strong>{target?.name}</strong> · {selected.id === 'retain' ? 'Keep the current mix.' : `Reshape ${selected.transitionPct.toFixed(1)}% of eligible assets (${exactMoney(selected.amount)}).`} All other accounts remain in the risk and income calculations.</p>
          {selected.sleeves.length > 0 && <div className="rec-sleeves">{selected.sleeves.map(s => <span key={s.id}><strong>{s.weight.toFixed(1)}%</strong>{s.label}</span>)}</div>}
          <p className="wealth-small">Sleeve weights apply to the amount reshaped, not the full account. They are illustrative building blocks, not named products or a Julius Baer approved list. Cash uses {reserveCurrency}; other new sleeves use USD proxies.</p>
          <Table className="wealth-table"><TableHeader><TableRow><TableHead>Asset class</TableHead><TableHead>Account now</TableHead><TableHead>Account after</TableHead><TableHead>Whole model after</TableHead></TableRow></TableHeader><TableBody>{rows.map(row => <TableRow key={row.asset}><TableCell>{row.asset}<small>Account range: {row.band.min}–{row.band.max}%</small></TableCell><TableCell>{row.current.toFixed(1)}%</TableCell><TableCell className={row.proposed < row.band.min - .05 || row.proposed > row.band.max + .05 ? 'wealth-negative' : ''}>{row.proposed.toFixed(1)}%</TableCell><TableCell>{row.whole.toFixed(1)}%</TableCell></TableRow>)}</TableBody></Table>
          <div className="rec-effect-summary"><Effect label={`${reserveCurrency} unpledged cash · USD equivalent`} before={money(report.before.reserveCash)} after={money(selected.metrics.reserveCash)} /><Effect label="Annual income after loan interest" before={`${money(report.before.income.netLow)}–${money(report.before.income.netHigh)}`} after={`${money(selected.metrics.income.netLow)}–${money(selected.metrics.income.netHigh)}`} /><Effect label="Largest direct position" before={`${report.before.topNamePct.toFixed(1)}%`} after={`${selected.metrics.topNamePct.toFixed(1)}%`} /><Effect label={selected.metrics.overlapLabel} before={`${report.before.overlapPct.toFixed(1)}%`} after={`${selected.metrics.overlapPct.toFixed(1)}%`} /></div>
          <details className="wealth-detail"><summary>Compare all five price and FX stress tests</summary><Table className="wealth-table"><TableHeader><TableRow><TableHead>Scenario</TableHead><TableHead>Current change</TableHead><TableHead>Proposed change</TableHead><TableHead>Difference</TableHead></TableRow></TableHeader><TableBody>{selected.metrics.tests.map(t => { const before = report.before.tests.find(s => s.id === t.id)!; return <TableRow key={t.id}><TableCell>{t.label}</TableCell><TableCell>{signed(before.change)}<small>{before.pct.toFixed(1)}%</small></TableCell><TableCell>{signed(t.change)}<small>{t.pct.toFixed(1)}%</small></TableCell><TableCell>{signed(t.change - before.change)}</TableCell></TableRow> })}</TableBody></Table><p>Same holding-level shocks as Stress & decisions. Private and outside-bank holdings remain in both sides. FX results use home-currency terms converted at the initial USD rate. No return forecast or historical outperformance is claimed.</p></details>
        </section>}

        <section className="wealth-card"><h3>What stops the RM from advising this?</h3><div className="rec-gates">{selected.gates.map(gate => <div key={gate.key} className={gate.pass ? 'rec-gate' : 'rec-gate rec-gate-failed'}>{gate.pass ? <Check size={17} /> : <LockKeyhole size={17} />}<div><strong>{gate.label}</strong><p>{gate.reason}</p></div><span>{gate.pass ? 'Pass in model' : 'Stop'}</span></div>)}</div><div className="wealth-note"><strong>These checks are still required for every option.</strong><p>Verify the complete wealth picture, account ownership, product eligibility, transaction costs, tax position, payment schedules and client consent. Missing fund or faith-based screening cannot be replaced by a score. A draft match never marks suitability as approved.</p></div></section>

        <section className="wealth-card"><h3>Trade-offs the RM must explain</h3><ul className="wealth-bullets">{selected.tradeoffs.map(text => <li key={text}>{text}</li>)}</ul>{requestedReturn && <p className="wealth-warning">Requested total return: {requestedReturn}% p.a. This is not scored because no calibrated total-return forecast is supplied. Ask how this target relates to acceptable losses and the time horizon.</p>}<p className="wealth-small">Lower income estimates remain estimates, not a capital-preservation promise. Pledged income may be retained by lenders. No tax saving is calculated.</p></section>
      </>}</div>
    </div>

    <div className="rec-bottom-grid">
      <section className="wealth-card"><h3>Use RM feedback to refine the match</h3><p>Adjust a stated goal, then compare again. This changes the current simulation; it does not train a model or change the client’s record.</p><div className="rec-feedback-controls"><div className="rec-field"><Label htmlFor="rec-feedback">Client wants more focus on</Label><NativeSelect id="rec-feedback" value={feedbackFocus} onChange={e => setFeedbackFocus(e.target.value as GoalKey)}>{goalKeys.map(k => <NativeSelectOption key={k} value={k}>{goalLabels[k]}</NativeSelectOption>)}</NativeSelect></div><button onClick={applyFeedback} className="action-secondary">Apply draft feedback</button></div><p className="wealth-small">Sets this priority to 5 and caps the others at 2. Reserve, horizon, loss, mandate and values constraints remain visible and must be satisfied.</p><div className="rec-field"><Label htmlFor="rec-outcome">RM decision on {selected.name}</Label><NativeSelect id="rec-outcome" value={outcome} onChange={e => setOutcome(e.target.value)}><NativeSelectOption disabled={selected.status === 'blocked'}>Shortlist for RM review</NativeSelectOption><NativeSelectOption>Request changes</NativeSelectOption><NativeSelectOption>Reject option</NativeSelectOption></NativeSelect></div><div className="rec-field"><Label htmlFor="rec-note">Reason and next check</Label><Textarea id="rec-note" value={note} maxLength={2000} onChange={e => setNote(e.target.value)} placeholder="Explain the goal fit, unresolved concern, and what must be confirmed next." /></div><button onClick={saveRationale} disabled={inputErrors.length > 0 || (selected.status === 'blocked' && outcome === 'Shortlist for RM review')} className="action-primary"><FileCheck2 size={16} />Save RM rationale</button>{saved && <p className="wealth-note" role="status">{saved}</p>}<p className="wealth-small">Saved reviews use the existing local decision ledger. No trade or client message is sent.</p></section>
      <section className="wealth-card"><h3>Evidence behind the match</h3><p>The engine uses this client’s records and the full included portfolio. No similar-client sales history, product popularity or bank revenue enters the score.</p>{report.evidence.map((item, index) => <details className="wealth-detail" key={item.source + index}><summary>{item.label} · {item.source}</summary><p>{item.text}</p></details>)}<details className="wealth-detail"><summary>Method, limits and research basis</summary><p>We use a constraint-based recommender: match stated requirements to defined portfolio attributes, filter failed gates, then rank the remaining options. This design is informed by <a href="https://tugraz.elsevierpure.com/ws/portalfiles/portal/72637700/3604915.3608819.pdf" target="_blank" rel="noreferrer">Lubos et al., ACM RecSys 2023</a>. <a href="https://recsys.acm.org/" target="_blank" rel="noreferrer">ACM RecSys</a> is the research community, not a portfolio API or an endorsement.</p><p>The search checked {report.searched} combinations: unchanged holdings, five standard mixes and a goal-funded core at 5% transition steps and the exact cash-reserve boundary, up to the entered cap. The goal-funded core first sets the reserve, then allocates remaining eligible assets toward account bands; frozen positions are subtracted before allocation. This is a bounded comparison, not an optimisation over all investments.</p><p>Each model retains its highest-scoring gate-passing transition. If none passes, the fewest-failures example is shown as blocked. Priorities and minimum horizons are transparent demo choices. No collaborative-filtering model is trained on these 20 synthetic clients.</p><p>Loss tests, cash-yield assumptions and source date are shared with the whole-wealth workbench. Detailed derivative payoffs, forecasts, currency hedges and full fund look-through are absent. Draft inputs reset when you leave the client; explicit saved reviews remain in this browser.</p><p>Cash and income goal achievement must be reviewed separately from behavioural risk willingness. Source-of-wealth overlap is an explicit sector proxy; it does not add unreported operating businesses to asset totals.</p></details></section>
    </div>
  </div>
}

function comparisonReason(selected: PortfolioRecommendation, other: PortfolioRecommendation) {
  if (selected.score === null || other.score === null) return 'A score comparison is unavailable because at least one option lacks a funded transition or usable goals. Resolve its stated restriction first.'
  if (selected.blocks.length) return `${selected.name} is not ranked: ${selected.blocks.map(g => g.label.toLowerCase()).join(', ')} failed. A higher score cannot override these constraints.`
  if (other.blocks.length) return `${other.name} is blocked by ${other.blocks.map(g => g.label.toLowerCase()).join(', ')}. Its score does not make it an eligible alternative.`
  const differences = selected.scoreParts.map(p => ({ label: p.label, delta: p.points - (other.scoreParts.find(o => o.key === p.key)?.points || 0) })).sort((a, b) => b.delta - a.delta)
  if (Math.abs(selected.score - other.score) < 1e-8) return 'These portfolios have equal calculated goal fit under the current priorities. The score is not adjusted to force a difference. The engine breaks ties by the smaller change amount, then a stable model identifier. Review their cash, income and scenario results.'
  const lead = differences[0]
  return selected.score > other.score ? `${selected.name} leads by ${points(selected.score - other.score)} match points. The largest contribution advantage is “${lead.label}” (${points(lead.delta)} points). Review the income and risk trade-offs below.` : `${other.name} ranks higher by ${points(other.score - selected.score)} points under the current priorities. This option still passes the model gates, so the RM can compare its trade-offs.`
}
function Effect({ label, before, after }: { label: string; before: string; after: string }) { return <div><span>{label}</span><p>{before}<ArrowRight size={15} aria-label="changes to" /><strong>{after}</strong></p></div> }
