"use client"

import { useState } from "react"
import { Activity, ArrowRight, CircleAlert, Info, Landmark, Scale } from "lucide-react"
import { FactCheckBubble } from "./fact-check-bubble"
import { fundingEvidence, interestEvidence, type Evidence } from "@/lib/calculation-evidence"
import { wealthFor } from "@/lib/wealth-model"
import type { InterventionModel, StressScenario } from "@/lib/types"

const palette = ["#141E55", "#717899", "#9FA3B9", "#D0D2DD", "#AFAA7D", "#007770"]

export function StressTest({ scenarios, allocationTitle, allocation, intervention }: { scenarios: StressScenario[]; allocationTitle: string; allocation: { label: string; value: number }[]; intervention?: InterventionModel }) {
  const [activeId, setActiveId] = useState(scenarios[0].id)
  const active = scenarios.find((scenario) => scenario.id === activeId) ?? scenarios[0]
  const maxDriver = Math.max(...active.drivers.map((driver) => Math.abs(driver.value)), 1)

  return <section className="mt-8 border border-border bg-card">
    <div className="border-b border-border p-5">
      <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><div className="flex items-center gap-2"><Activity className="size-4" /><h2 className="text-sm font-semibold">Scenario analysis and decision support</h2></div><p className="mt-1 text-xs text-muted-foreground">Select a scenario to compare the current position, estimated effect, and suggested response.</p></div><div className="flex flex-wrap gap-2">{scenarios.map((scenario) => <button key={scenario.id} onClick={() => setActiveId(scenario.id)} className={scenario.id === active.id ? "scenario-active" : "scenario-idle"}>{scenario.label}</button>)}</div></div>
      <div className="scenario-change mt-5">
        <ScenarioPoint label="Current" value={active.comparison.current} evidence={active.id === "ravi-rates" ? () => interestEvidence(wealthFor("CL-0002"), { facilityId: "CF-0001" }) : undefined} revision={active.id} />
        <ArrowRight className="scenario-arrow" />
        <ScenarioPoint label="Estimated scenario" value={active.comparison.stressed} tone="critical" evidence={active.id === "ravi-rates" ? () => interestEvidence(wealthFor("CL-0002"), { facilityId: "CF-0001", shockBps: 100 }) : active.id === "ravi-delay" ? () => interestEvidence(wealthFor("CL-0002"), { months: 6 }) : undefined} revision={active.id} />
        <ArrowRight className="scenario-arrow" />
        <ScenarioPoint label="With suggested action" value={active.comparison.afterAction} note={active.comparison.afterActionNote} tone="action" />
      </div>
    </div>

    <div className="grid border-b border-border lg:grid-cols-[0.86fr_1.14fr]">
      <div className="border-b border-border p-5 lg:border-b-0 lg:border-r"><p className="eyebrow">Estimated effect</p><p className="mt-3 text-3xl font-normal tracking-tight text-primary">{active.impactLabel}</p><p className="mt-1 text-xs text-muted-foreground">{active.portfolioImpactPct.toFixed(2)}% of current wealth</p><p className="mt-5 border-l-2 border-primary pl-4 text-sm font-medium leading-6">{active.result}</p><p className="mt-4 flex items-start gap-2 text-xs leading-5 text-muted-foreground"><Info className="mt-0.5 size-3.5 shrink-0" />{active.detail}</p><div className="mt-6"><div className="flex items-center justify-between"><p className="eyebrow">Impact drivers</p><span className="text-[11px] text-muted-foreground">% of wealth</span></div><div className="mt-4 space-y-3">{active.drivers.map((driver) => { const width = Math.abs(driver.value) / maxDriver * 48; const left = driver.value < 0 ? 50 - width : 50; return <div key={driver.label} className="grid grid-cols-[112px_1fr_48px] items-center gap-3 text-xs"><span>{driver.label}</span><div className="sensitivity-track"><span className="sensitivity-zero" /><span className={driver.value < 0 ? "sensitivity-negative" : "sensitivity-positive"} style={{ left: `${left}%`, width: `${width}%` }} /></div><strong className="text-right">{driver.value > 0 ? "+" : ""}{driver.value.toFixed(2)}</strong></div>})}</div></div><div className="mt-6 grid gap-2 sm:grid-cols-3">{active.components.map((item) => <div key={item} className="border-t border-[#9FA3B9] bg-[#F5F5F2] p-3 text-xs font-medium leading-5">{item}</div>)}</div></div>
      <div className="p-5"><div className="flex items-center gap-2"><Scale className="size-4 text-primary" /><p className="eyebrow">RM decision tool</p>{active.id === "ravi-delay" && <FactCheckBubble title="trust and six-month interest reserve" derive={() => fundingEvidence(wealthFor("CL-0002"), 2000000, "planned_cash_needs.csv: CN-003 · family trust funding, likely")} revision={active.id} />}</div><h3 className="mt-2 text-2xl font-normal text-primary">{active.decision.title}</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{active.decision.summary}</p><div className="mt-5 space-y-2">{active.decision.rebalance.map((item, index) => <div key={`${item.action}-${index}`} className="rebalance-row"><span>0{index + 1}</span><div><div className="flex flex-col justify-between gap-1 sm:flex-row"><strong>{item.action}</strong><b>{item.amount}</b></div><p>{item.rationale}</p></div></div>)}</div><div className="mt-6 grid gap-5 sm:grid-cols-2"><div><p className="eyebrow">Why this helps</p><ol className="mt-3 space-y-2">{active.decision.reasoning.map((reason, index) => <li key={reason} className="flex gap-2 text-xs leading-5"><span className="font-bold text-muted-foreground">{index + 1}</span><span>{reason}</span></li>)}</ol></div><div className="tax-opportunity"><div className="flex items-center gap-2"><Landmark className="size-3.5" /><p className="eyebrow">Tax-aware review</p></div><strong>{active.decision.taxOpportunity.title}</strong><p>{active.decision.taxOpportunity.detail}</p><small>{active.decision.taxOpportunity.guardrail}</small></div></div></div>
    </div>

    {intervention && <div className="intervention-shell">
      <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div><p className="eyebrow">{intervention.label}</p><h3 className="mt-2 text-2xl font-normal text-primary">Turn the warning into agreed actions</h3></div><p className="intervention-alert"><CircleAlert className="mt-0.5 size-4 shrink-0" />{intervention.observedAction}</p></div>
      <div className="mt-6 grid gap-px border border-border bg-border md:grid-cols-3">{intervention.metrics.map((metric) => <div key={metric.label} className="intervention-metric"><p className="eyebrow">{metric.label}</p><p className={metric.tone === "critical" ? "text-destructive" : metric.tone === "warn" ? "text-[#655f34]" : "text-primary"}>{metric.value}</p><span>{metric.note}</span></div>)}</div>
      <div className="mt-7 grid gap-7 lg:grid-cols-2"><div><p className="eyebrow">Secondary sale confidence</p><div className="mt-3 grid grid-cols-2 gap-px border border-border bg-border sm:grid-cols-4">{intervention.saleStages.map((stage, index) => <div key={stage.label} className={stage.state === "current" ? "sale-stage sale-stage-current" : "sale-stage"}><span>0{index + 1}</span><strong>{stage.label}</strong><small>{stage.state === "current" ? "Current evidence" : "Not yet"}</small></div>)}</div><p className="mt-3 text-xs leading-5 text-muted-foreground">Do not count expected proceeds as liquidity until the sale is signed and cash has settled.</p></div><div><p className="eyebrow">Pre-agreed control ladder</p><div className="mt-3 border-y border-border">{intervention.controls.map((control, index) => <div key={control.level} className="control-row"><span>0{index + 1}</span><div><strong>{control.level}</strong><p>{control.action}</p></div></div>)}</div></div></div>
      <div className="mt-7"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><p className="eyebrow">Collateral cure table</p><h3 className="mt-1 text-lg font-normal text-primary">If technology collateral falls again</h3></div><p className="text-xs text-muted-foreground">Repayment and added collateral are alternative cures, not additive.</p></div><div className="mt-3 overflow-x-auto border border-border"><table className="cure-table"><thead><tr><th>Scenario</th><th>LTV</th><th>Debt repayment</th><th>Eligible lending-value gap</th></tr></thead><tbody>{intervention.collateralStress.map((row) => <tr key={row.shock}><td>{row.shock}</td><td>{row.ltv}</td><td>{row.repayment}</td><td>{row.collateralGap}</td></tr>)}</tbody></table></div></div>
    </div>}

    <div className="bg-[#EFEEE5] p-5"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Exposure model</p><h3 className="mt-1 text-lg font-normal text-primary">{allocationTitle}</h3></div><span className="text-xs text-muted-foreground">100% of wealth</span></div><div className="mt-4 flex h-8 w-full overflow-hidden" aria-label={allocation.map((item) => `${item.label} ${item.value}%`).join(", ")}>{allocation.map((item, index) => <div key={item.label} className="h-full" style={{ width: `${item.value}%`, backgroundColor: palette[index % palette.length] }} title={`${item.label}: ${item.value.toFixed(2)}%`} />)}</div><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2">{allocation.map((item, index) => <div key={item.label} className="flex items-center gap-2 text-xs"><span className="size-2.5" style={{ backgroundColor: palette[index % palette.length] }} /><span>{item.label}</span><strong>{item.value.toFixed(1)}%</strong></div>)}</div></div>
  </section>
}

function ScenarioPoint({ label, value, note, tone = "neutral", evidence, revision }: { label: string; value: string; note?: string; tone?: "neutral" | "critical" | "action"; evidence?: () => Evidence; revision?: string }) {
  return <div className={`scenario-point scenario-point-${tone}`}><p>{label}</p><strong>{value}</strong>{evidence && <FactCheckBubble title={`${label} loan interest`} derive={evidence} revision={revision} />}{note && <span>{note}</span>}</div>
}
