import { clearance } from "@/lib/rules/clearance"
import type { ClientProfile, RiskKind, StressScenario } from "@/lib/types"

type Seed = {
  slug: string; id: string; name: string; context: string; source: string; objectives: string
  aumM: number; risk: string; base: string; language: string; tax: string; primaryRisk: RiskKind
  allocation: { label: string; value: number }[]; topName: string; topPct: number
  dailyPct: number; cashPct: number; nonBasePct: number; gainM: number; lossM: number
  needLabel: string; needAmountM: number; stance: string; opening: string; likelyAsk: string
  actionTitle: string; actionBody: string; steps: string[]; avoidTitle: string; avoidReason: string
  nextReview: string; priority?: "Action" | "Watch"; clearance?: "GREEN" | "AMBER"
}

const usd = (value: number) => `USD ${value.toFixed(value < 1 ? 2 : 1)}m`

function taxReview(seed: Seed) {
  if (seed.lossM > 0.05) return {
    title: `Review ${usd(seed.lossM)} of loss positions`,
    detail: `Compare the identified losses with approximately ${usd(seed.gainM)} of gains when selecting lots. Tax domicile: ${seed.tax}.`,
    guardrail: "Confirm local tax treatment, holding periods, costs, and suitability before any trade.",
  }
  return {
    title: "Review gain timing and cost basis",
    detail: `The snapshot shows limited unrealised losses and approximately ${usd(seed.gainM)} of gains. Tax domicile: ${seed.tax}.`,
    guardrail: "Do not assume that loss offsets or capital-gains exemptions apply. Obtain tax advice.",
  }
}

function genericScenarios(seed: Seed): StressScenario[] {
  const equityPct = seed.allocation.find((item) => item.label === "Equity")?.value ?? 0
  const equityLoss = seed.aumM * equityPct / 100 * 0.10
  const fxLoss = seed.aumM * seed.nonBasePct / 100 * 0.10
  const currentCash = seed.aumM * seed.cashPct / 100
  const needAmount = seed.needAmountM || seed.aumM * 0.05
  const gap = Math.max(0, needAmount - currentCash)
  const shift = seed.aumM * 0.03
  const tax = taxReview(seed)
  return [
    {
      id: `${seed.id}-equity`, label: "Equity −10%", impactLabel: `−${usd(equityLoss)}`,
      portfolioImpactPct: equityLoss / seed.aumM * 100,
      result: `Estimated wealth falls from ${usd(seed.aumM)} to ${usd(seed.aumM - equityLoss)}.`,
      detail: "Applies a 10% shock to the disclosed equity sleeve. Other assets and currency effects are unchanged.",
      components: [`Equity sleeve ${equityPct.toFixed(1)}%`, `Estimated loss ${usd(equityLoss)}`, `Largest position ${seed.topPct.toFixed(1)}%`],
      drivers: [{ label: "Equity sleeve", value: -(equityLoss / seed.aumM * 100) }],
      comparison: { current: usd(seed.aumM), stressed: usd(seed.aumM - equityLoss), afterAction: `Risk sleeve −${usd(shift)}`, afterActionNote: "Illustrative 3% rebalance reduces repeat-shock exposure" },
      decision: {
        title: "Reduce the largest repeat-shock driver", summary: "Keep the strategic allocation, but reduce the concentration that contributes most to the scenario loss.",
        rebalance: [{ action: `Trim or hedge ${seed.topName}`, amount: `${usd(shift)} review`, rationale: "Moves 3% of wealth away from the largest disclosed concentration." }, { action: "Add short-duration or diversified assets", amount: `${usd(shift)} target`, rationale: "Creates a liquid counterweight without a full portfolio change." }],
        reasoning: [`Equity is ${equityPct.toFixed(1)}% of wealth.`, `${seed.topName} is ${seed.topPct.toFixed(1)}% of wealth.`, "The suggestion is sized as a review point, not an automatic trade."], taxOpportunity: tax,
      },
    },
    {
      id: `${seed.id}-fx`, label: `${seed.base} +10%`, impactLabel: `−${usd(fxLoss)}`,
      portfolioImpactPct: fxLoss / seed.aumM * 100,
      result: `${seed.nonBasePct.toFixed(1)}% of assets are outside the reporting currency.`,
      detail: `Illustrative translation shock if ${seed.base} strengthens 10% against non-base assets; hedges and cross-rates are excluded.`,
      components: [`Non-base assets ${seed.nonBasePct.toFixed(1)}%`, `Estimated translation effect ${usd(fxLoss)}`, `Base currency ${seed.base}`],
      drivers: [{ label: "Non-base assets", value: -(fxLoss / seed.aumM * 100) }],
      comparison: { current: usd(seed.aumM), stressed: usd(seed.aumM - fxLoss), afterAction: `FX effect ≈ −${usd(fxLoss / 2)}`, afterActionNote: "Illustrative 50% hedge of the exposed sleeve" },
      decision: {
        title: "Match the next liability before hedging the full book", summary: `Prioritise the currency of ${seed.needLabel.toLowerCase()} before broad portfolio hedging.`,
        rebalance: [{ action: `Build a ${seed.base} liability reserve`, amount: `${usd(Math.min(needAmount, Math.max(shift, needAmount * 0.5)))} review`, rationale: "Matches a known need and reduces conversion-date risk." }],
        reasoning: [`${seed.nonBasePct.toFixed(1)}% is outside ${seed.base}.`, "Known liabilities have less flexibility than long-term investments.", "A staged hedge reduces timing risk while preserving market participation."], taxOpportunity: tax,
      },
    },
    {
      id: `${seed.id}-liquidity`, label: "Liquidity need", impactLabel: gap > 0 ? `${usd(gap)} cash gap` : "Covered by cash",
      portfolioImpactPct: gap / seed.aumM * 100,
      result: `${seed.needLabel}; current cash is about ${usd(currentCash)}.`,
      detail: "Compares the stated need with cash only. Coupons, maturities, credit availability, tax, and settlement dates require review.",
      components: [`Known need ${usd(needAmount)}`, `Current cash ${usd(currentCash)}`, gap > 0 ? `Cash-only gap ${usd(gap)}` : "No cash-only gap"],
      drivers: [{ label: "Cash-only gap", value: -(gap / seed.aumM * 100) }],
      comparison: { current: `Cash ${usd(currentCash)}`, stressed: `Need ${usd(needAmount)}`, afterAction: "Need ring-fenced", afterActionNote: "Use cash, maturities, and selected sales in sequence" },
      decision: {
        title: "Create a dated funding plan", summary: "Do not wait for the payment date to decide which assets must be sold.",
        rebalance: [{ action: "Ring-fence the next known need", amount: usd(needAmount), rationale: "Separates near-term spending from the long-term portfolio." }, { action: "Use coupons, maturities, then selected sales", amount: gap > 0 ? `${usd(gap)} gap` : "No current cash gap", rationale: "Reduces forced-sale and settlement risk." }],
        reasoning: [`Current cash is ${seed.cashPct.toFixed(1)}% of wealth.`, `Daily liquidity is ${seed.dailyPct.toFixed(1)}% of wealth.`, "Funding sources must be mapped to the due date and currency."], taxOpportunity: tax,
      },
    },
  ]
}

function profile(seed: Seed): ClientProfile {
  const total = seed.allocation.reduce((sum, item) => sum + item.value, 0)
  const allocation = seed.allocation.map((item) => ({ ...item, value: item.value / total * 100 }))
  return {
    slug: seed.slug, id: seed.id, name: seed.name, context: seed.context, sourceOfWealth: seed.source,
    objectives: seed.objectives, aum: seed.base === "USD" ? usd(seed.aumM) : `${usd(seed.aumM)} eq.`,
    riskProfile: seed.risk, baseCurrency: seed.base, reportingLanguage: seed.language, taxDomicile: seed.tax,
    priority: seed.priority ?? "Watch", primaryRisk: seed.primaryRisk, nextReview: seed.nextReview,
    allocationTitle: "Current total wealth mix", allocation,
    signals: [
      { label: "Largest position", value: `${seed.topPct.toFixed(1)}%`, note: seed.topName, tone: seed.topPct >= 20 ? "critical" : seed.topPct >= 15 ? "warn" : "neutral" },
      { label: "Daily liquidity", value: `${seed.dailyPct.toFixed(1)}%`, note: seed.needLabel, tone: seed.dailyPct < 65 ? "warn" : "neutral" },
      { label: "Outside base currency", value: `${seed.nonBasePct.toFixed(1)}%`, note: `Base ${seed.base} · tax domicile ${seed.tax}`, tone: seed.nonBasePct > 50 ? "warn" : "neutral" },
    ],
    likelyAsk: seed.likelyAsk, clientStance: seed.stance, rmOpening: seed.opening,
    action: { title: seed.actionTitle, status: seed.clearance ?? "GREEN", body: seed.actionBody, steps: seed.steps, checks: clearance(seed.clearance ?? "GREEN") },
    avoid: { title: seed.avoidTitle, reason: seed.avoidReason }, scenarios: genericScenarios(seed), insightIds: [],
  }
}

const seeds: Seed[] = [
  { slug: "hartono-wijaya-kusuma", id: "CL-0001", name: "Hartono Wijaya Kusuma", context: "Second generation · family energy group", source: "Inherited wealth from a family coal mining and energy group.", objectives: "Preserve family wealth outside Indonesia, diversify from the operating business, and fund a Singapore property purchase in 2027.", aumM: 46.57, risk: "Balanced Growth", base: "SGD", language: "English", tax: "Indonesia", primaryRisk: "Currency", allocation: [{label:"Equity",value:70.4},{label:"Fixed Income",value:14.5},{label:"Alternatives",value:4.2},{label:"Cash and Equivalents",value:3.7},{label:"Commodities",value:3.7},{label:"Structured Products",value:3.6}], topName: "Bara Nusantara Energy", topPct: 41.4, dailyPct: 89.4, cashPct: 3.7, nonBasePct: 97.1, gainM: 18.08, lossM: 0.12, needLabel: "SGD 9.0m property deposit", needAmountM: 6.6, stance: "Wants more energy exposure and does not want to reduce the family-linked holding.", opening: "Let us secure the SGD property payment first, then decide how much risk is available for new energy ideas.", likelyAsk: "How can I add energy exposure and still fund the Singapore property?", actionTitle: "Pre-fund the SGD property deposit", actionBody: "Stage the currency conversion and reduce the overlap between family wealth, the custody holding, and new energy products.", steps: ["Set the SGD funding dates", "Review the 41.4% energy holding", "Test the facility after an energy reversal"], avoidTitle: "Do not add another energy product first", avoidReason: "It increases the same source-of-wealth and collateral risk before the SGD liability is funded.", nextReview: "Today", priority: "Action", clearance: "AMBER" },
  { slug: "margarethe-voss-brenner", id: "CL-0003", name: "Margarethe Voss-Brenner", context: "Recently inherited · transition", source: "Inherited her late spouse’s industrial holding in February 2026.", objectives: "Understand and de-risk the inherited portfolio, secure stable income, and plan for German inheritance tax.", aumM: 22.18, risk: "Conservative", base: "EUR", language: "German", tax: "Germany", primaryRisk: "Mandate", allocation: [{label:"Equity",value:71.5},{label:"Fixed Income",value:9.1},{label:"Cash and Equivalents",value:7.7},{label:"Alternatives",value:6.3},{label:"Structured Products",value:5.4}], topName: "Global Luxury and Consumer Brands Fund", topPct: 26.1, dailyPct: 88.3, cashPct: 7.7, nonBasePct: 25.6, gainM: 2.86, lossM: 0.25, needLabel: "EUR 3.4m inheritance tax", needAmountM: 3.7, stance: "Wants something safe and understandable and has asked not to make abrupt changes.", opening: "We can fund the tax payment and reduce risk in controlled stages, with each step explained before action.", likelyAsk: "Can you make this portfolio safer without making large changes all at once?", actionTitle: "Fund tax and restore the conservative mandate", actionBody: "Coordinate the inheritance-tax reserve with a staged reduction in equity concentration.", steps: ["Ring-fence the confirmed tax amount", "Reduce the largest equity positions in stages", "Rebuild fixed income within mandate"], avoidTitle: "Do not present a complex product solution", avoidReason: "The client has asked for safe, clear holdings and needs confidence before portfolio complexity.", nextReview: "Today", priority: "Action", clearance: "AMBER" },
  { slug: "chalermchai-suphanburi", id: "CL-0004", name: "Chalermchai Suphanburi", context: "Pre-retirement · agribusiness founder", source: "Entrepreneurial wealth from agribusiness and food processing.", objectives: "Replace salary with portfolio income from Q2 2027, fund a family foundation, and transfer the business to the next generation.", aumM: 33.45, risk: "Income", base: "USD", language: "English", tax: "Thailand", primaryRisk: "Duration", allocation: [{label:"Fixed Income",value:64.7},{label:"Equity",value:23.8},{label:"Cash and Equivalents",value:6.1},{label:"Alternatives",value:5.4}], topName: "Global Investment Grade Corporate Bond Fund", topPct: 16.0, dailyPct: 83.2, cashPct: 6.1, nonBasePct: 9.7, gainM: 1.26, lossM: 5.72, needLabel: "USD 1.45m annual retirement income", needAmountM: 1.45, stance: "Asked whether he should move everything to deposits after reading about interest rates.", opening: "Deposits can fund near-term income, but moving everything would replace duration risk with reinvestment risk.", likelyAsk: "Should I move the portfolio to deposits before retirement?", actionTitle: "Build a retirement income ladder", actionBody: "Fund the first two years of withdrawals while keeping a diversified income sleeve.", steps: ["Map 24 months of income", "Compare bond duration with deposit reinvestment", "Review the largest bond fund"], avoidTitle: "Do not answer with an all-or-nothing switch", avoidReason: "A full move to deposits may not support long-term income or inflation protection.", nextReview: "This week" },
  { slug: "aishah-binti-rahman", id: "CL-0005", name: "Aishah binti Rahman", context: "Peak earning years · sustainable mandate", source: "Entrepreneurial wealth from palm oil plantations and commercial property.", objectives: "Align with the family sustainability policy, diversify from plantation assets, and fund education in Australia.", aumM: 19.40, risk: "Sustainable Balanced", base: "SGD", language: "English", tax: "Malaysia", primaryRisk: "Mandate", allocation: [{label:"Equity",value:67.7},{label:"Fixed Income",value:26.5},{label:"Cash and Equivalents",value:5.7}], topName: "Global Developed Equity Index Fund", topPct: 14.7, dailyPct: 94.3, cashPct: 5.7, nonBasePct: 61.3, gainM: 3.64, lossM: 0.32, needLabel: "SGD 0.18m annual university fees", needAmountM: 0.13, stance: "Believes the portfolio is fully aligned and did not know about the excluded energy fund.", opening: "Let us separate the legacy family holding from the binding sustainability rules and correct the mandate exposure.", likelyAsk: "Is my portfolio fully aligned with the family sustainability policy?", actionTitle: "Resolve the sustainability exception", actionBody: "Confirm the policy scope, remove any binding exclusion breach, and document treatment of the legacy holding.", steps: ["Show the excluded exposure", "Confirm policy treatment of the legacy holding", "Fund AUD education costs"], avoidTitle: "Do not describe the mandate as fully aligned", avoidReason: "The energy holding conflicts with the stated policy until an exception or change is documented.", nextReview: "This week", clearance: "AMBER" },
  { slug: "nguyen-thi-bao-tran", id: "CL-0006", name: "Nguyen Thi Bao Tran", context: "Wealth accumulation · manufacturing founder", source: "Entrepreneurial wealth from electronics contract manufacturing.", objectives: "Meet USD private-equity calls and US university fees while growing capital at a moderate pace.", aumM: 18.07, risk: "Balanced", base: "SGD", language: "English", tax: "Singapore", primaryRisk: "Liquidity", allocation: [{label:"Equity",value:40.2},{label:"Fixed Income",value:29.0},{label:"Alternatives",value:19.3},{label:"Cash and Equivalents",value:11.5}], topName: "Singapore Government Securities 2036", topPct: 22.5, dailyPct: 69.2, cashPct: 11.5, nonBasePct: 26.8, gainM: 1.12, lossM: 0.74, needLabel: "USD 8.0m fees and capital calls", needAmountM: 8.0, stance: "Was surprised that a private credit fund could gate withdrawals.", opening: "We should map every USD payment to a dated source and avoid relying on gated assets.", likelyAsk: "How will I meet tuition and capital calls if the private fund remains gated?", actionTitle: "Build a USD liquidity schedule", actionBody: "Match capital calls and tuition to cash, maturities, and daily assets by date.", steps: ["List each call and tuition date", "Exclude gated assets from available liquidity", "Stage SGD-to-USD conversion"], avoidTitle: "Do not count gated funds as available cash", avoidReason: "Redemption timing is controlled by the fund, not the client.", nextReview: "This week", clearance: "AMBER" },
  { slug: "alistair-pemberton-hale", id: "CL-0007", name: "Alistair Pemberton-Hale", context: "Retired · legacy and philanthropy", source: "Executive compensation from a career in physical commodities trading.", objectives: "Fund a charitable foundation, leave a defined legacy, and protect real purchasing power.", aumM: 40.02, risk: "Balanced", base: "USD", language: "English", tax: "United Kingdom", primaryRisk: "Liquidity", allocation: [{label:"Equity",value:36.0},{label:"Fixed Income",value:29.0},{label:"Commodities",value:18.9},{label:"Alternatives",value:7.0},{label:"Structured Products",value:5.1},{label:"Cash and Equivalents",value:4.0}], topName: "Global Developed Equity Index Fund", topPct: 13.1, dailyPct: 87.9, cashPct: 4.0, nonBasePct: 7.0, gainM: 9.72, lossM: 0.39, needLabel: "USD 12.0m foundation endowment", needAmountM: 12.0, stance: "Wants to fund the foundation from appreciated assets; UK tax questions are unresolved.", opening: "Before selecting assets for the gift, let us resolve the UK tax and foundation structure.", likelyAsk: "Which appreciated assets should fund the foundation?", actionTitle: "Design the tax-aware endowment transfer", actionBody: "Coordinate the asset selection, foundation timing, and legacy plan before disposal.", steps: ["Bring in wealth planning", "Compare gifting and sale routes", "Reserve the 2027 endowment"], avoidTitle: "Do not sell appreciated assets before the structure review", avoidReason: "The tax and charitable outcome can depend on the transfer sequence.", nextReview: "This month", clearance: "AMBER" },
  { slug: "chen-wei-ling", id: "CL-0008", name: "Chen Wei Ling", context: "Peak earning years · F&B founder", source: "Entrepreneurial wealth from a food and beverage franchise business.", objectives: "Fund overseas university education, prepare for a partial business sale, and achieve steady growth.", aumM: 11.95, risk: "Balanced", base: "SGD", language: "English", tax: "Singapore", primaryRisk: "Liquidity", allocation: [{label:"Equity",value:49.7},{label:"Fixed Income",value:32.4},{label:"Cash and Equivalents",value:13.6},{label:"Commodities",value:4.3}], topName: "Singapore Government Securities 2036", topPct: 17.0, dailyPct: 86.4, cashPct: 13.6, nonBasePct: 43.8, gainM: 1.44, lossM: 0.34, needLabel: "SGD 0.42m annual education costs", needAmountM: 0.31, stance: "Wants certainty for six years of education costs and accepts lower returns on that sleeve.", opening: "We can separate the education portfolio from long-term growth and match each school year.", likelyAsk: "Can you make the education funding certain without moving the full portfolio to cash?", actionTitle: "Create a six-year education ladder", actionBody: "Match each annual payment with SGD cash and short maturities while keeping the balance invested.", steps: ["Confirm annual fee dates", "Create the SGD ladder", "Keep the 2028 business sale outside the base plan"], avoidTitle: "Do not rely on the 2028 business sale", avoidReason: "The education costs start before the possible sale is certain.", nextReview: "This month" },
  { slug: "andreas-lindqvist", id: "CL-0009", name: "Andreas Lindqvist", context: "Post-liquidity event · industrialist", source: "Proceeds from the 2024 sale of a majority stake in an industrial group.", objectives: "Deploy sale proceeds, retain a residual business stake, and prepare to retire in Europe.", aumM: 31.61, risk: "Balanced", base: "EUR", language: "English", tax: "Sweden", primaryRisk: "Concentration", allocation: [{label:"Cash and Equivalents",value:45.0},{label:"Equity",value:33.4},{label:"Fixed Income",value:14.5},{label:"Alternatives",value:7.2}], topName: "EUR Call Deposit", topPct: 33.9, dailyPct: 92.8, cashPct: 45.0, nonBasePct: 29.1, gainM: 3.94, lossM: 0.29, needLabel: "USD 1.1m private-market commitment", needAmountM: 1.1, stance: "Agreed an allocation twice but continues to wait for a better entry point.", opening: "Let us replace the market-timing decision with a dated deployment rule you can stop or adjust.", likelyAsk: "How do I invest without choosing the wrong entry point?", actionTitle: "Use a rules-based deployment schedule", actionBody: "Move excess cash into the agreed allocation in measured tranches while reserving commitments.", steps: ["Ring-fence the commitment", "Agree tranche dates and limits", "Review the sentimental residual holding separately"], avoidTitle: "Do not propose another target allocation only", avoidReason: "The allocation is already agreed; execution behaviour is the unresolved risk.", nextReview: "This month" },
  { slug: "priya-nair-menon", id: "CL-0010", name: "Priya Nair Menon", context: "Next generation · impact investor", source: "A family-trust distribution received in 2024.", objectives: "Pursue long-horizon growth under a personal impact policy and buy a first property in 2028.", aumM: 8.18, risk: "Sustainable Balanced", base: "SGD", language: "English", tax: "Singapore", primaryRisk: "Currency", allocation: [{label:"Equity",value:49.6},{label:"Fixed Income",value:36.7},{label:"Alternatives",value:7.3},{label:"Cash and Equivalents",value:6.3}], topName: "Singapore Government Securities 2036", topPct: 21.6, dailyPct: 86.3, cashPct: 6.3, nonBasePct: 72.1, gainM: 0.90, lossM: 0.14, needLabel: "2028 first-property reserve", needAmountM: 0.41, stance: "Reviews sustainability screens closely and has no current concern.", opening: "Your portfolio is on plan; the next useful step is to define the size and currency of the 2028 property fund.", likelyAsk: "When should I start separating the property fund from long-term growth?", actionTitle: "Define the 2028 property reserve", actionBody: "Set the target deposit and gradually move that amount into SGD assets as the date approaches.", steps: ["Estimate the property deposit", "Set annual funding steps", "Keep sustainability screens documented"], avoidTitle: "Do not hedge the full long-term portfolio", avoidReason: "Only the known SGD liability needs near-term currency certainty.", nextReview: "Next quarter" },
  { slug: "tan-boon-huat", id: "CL-0011", name: "Tan Boon Huat", context: "Succession · property founder", source: "Entrepreneurial wealth from property development.", objectives: "Transfer assets to four children, maintain income, and avoid disruption to the family property portfolio.", aumM: 35.34, risk: "Conservative", base: "SGD", language: "English", tax: "Singapore", primaryRisk: "Liquidity", allocation: [{label:"Alternatives",value:47.3},{label:"Fixed Income",value:24.5},{label:"Equity",value:21.6},{label:"Cash and Equivalents",value:6.7}], topName: "Asia Real Estate Opportunity Fund III", topPct: 20.4, dailyPct: 46.0, cashPct: 6.7, nonBasePct: 23.6, gainM: 5.57, lossM: 0.81, needLabel: "SGD 2.8m estate and legal costs", needAmountM: 2.06, stance: "Has delayed the succession structure four times despite declining health.", opening: "The next decision is not the final structure. It is who can act and fund costs if you cannot.", likelyAsk: "Can I keep control while preventing a forced property sale?", actionTitle: "Set an interim succession safeguard", actionBody: "Secure authority, liquidity, and a family decision process before finalising the full structure.", steps: ["Confirm decision authority", "Reserve estate and legal costs", "Map illiquid property ownership"], avoidTitle: "Do not wait for complete family agreement", avoidReason: "An interim safeguard is needed while the final structure remains unresolved.", nextReview: "This week", clearance: "AMBER" },
  { slug: "zhang-meiling", id: "CL-0013", name: "Zhang Meiling", context: "Wealth accumulation · e-commerce founder", source: "Entrepreneurial wealth from a cross-border e-commerce platform.", objectives: "Pursue aggressive growth, maintain business-investment credit, and establish a family office later.", aumM: 36.95, risk: "Growth", base: "USD", language: "Simplified Chinese", tax: "Hong Kong SAR", primaryRisk: "Concentration", allocation: [{label:"Equity",value:75.7},{label:"Structured Products",value:7.1},{label:"Alternatives",value:6.5},{label:"Fixed Income",value:5.5},{label:"Cash and Equivalents",value:5.1}], topName: "US Technology Leaders Fund", topPct: 22.4, dailyPct: 86.4, cashPct: 5.1, nonBasePct: 8.9, gainM: 10.36, lossM: 0.36, needLabel: "Opportunistic business liquidity", needAmountM: 1.85, stance: "Views the technology drawdown as a buying opportunity and disputes look-through concentration.", opening: "Your sector knowledge is an advantage; the control is how much portfolio and collateral exposure can share the same outcome.", likelyAsk: "How much more technology can I add without limiting the credit line?", actionTitle: "Set a look-through technology limit", actionBody: "Aggregate direct holdings and structured-product underlyings before approving new exposure.", steps: ["Show direct and look-through exposure", "Set a credit-linked concentration limit", "Retain business liquidity"], avoidTitle: "Do not debate her sector expertise", avoidReason: "Focus on portfolio capacity and collateral mechanics, not who has the better technology view.", nextReview: "This week", clearance: "AMBER" },
  { slug: "lau-chi-ming", id: "CL-0014", name: "Lau Chi Ming", context: "Peak earning years · property developer", source: "Entrepreneurial wealth from Hong Kong residential and commercial property development.", objectives: "Generate yield, retain exposure to a Hong Kong property recovery, and fund a Mid-Levels redevelopment.", aumM: 26.49, risk: "Balanced", base: "HKD", language: "Traditional Chinese", tax: "Hong Kong SAR", primaryRisk: "Collateral", allocation: [{label:"Fixed Income",value:44.2},{label:"Equity",value:23.4},{label:"Alternatives",value:19.6},{label:"Structured Products",value:7.0},{label:"Cash and Equivalents",value:5.8}], topName: "Direct Property – Mid-Levels Apartment", topPct: 19.6, dailyPct: 42.9, cashPct: 5.8, nonBasePct: 44.2, gainM: 1.60, lossM: 8.02, needLabel: "HKD 60.0m redevelopment equity", needAmountM: 7.69, stance: "Expected to fund the project from the portfolio and was surprised by low usable liquidity.", opening: "Your contractual credit and sellable liquidity are different; let us fund the project without crossing the 70% trigger.", likelyAsk: "How can I fund the redevelopment without selling Hong Kong property exposure?", actionTitle: "Close the redevelopment funding gap", actionBody: "Separate daily liquidity from illiquid assets and act before the Lombard facility reaches its trigger.", steps: ["Map HKD funding dates", "Set an RM control below 70% LTV", "Review loss positions and settlement timing"], avoidTitle: "Do not use the remaining credit limit as liquidity", avoidReason: "Current LTV is already 69.4% against a 70% trigger.", nextReview: "This week", clearance: "AMBER" },
  { slug: "kim-do-yoon", id: "CL-0015", name: "Kim Do-Yoon", context: "Dynamic · media entrepreneur", source: "Entrepreneurial wealth from media production and artist management.", objectives: "Seek high growth through thematic and event-driven ideas with accepted drawdown risk.", aumM: 14.99, risk: "Dynamic Opportunistic", base: "USD", language: "English", tax: "Republic of Korea", primaryRisk: "Concentration", allocation: [{label:"Equity",value:46.6},{label:"Alternatives",value:21.9},{label:"Structured Products",value:12.8},{label:"Commodities",value:7.5},{label:"Cash and Equivalents",value:7.0},{label:"Fixed Income",value:4.1}], topName: "US Technology Leaders Fund", topPct: 19.8, dailyPct: 65.2, cashPct: 7.0, nonBasePct: 7.6, gainM: 1.96, lossM: 0.00, needLabel: "Opportunistic liquidity reserve", needAmountM: 0.75, stance: "Understands worst-of structures and wants aggressive Middle East event exposure.", opening: "We can express the view, but first set a total worst-of and event-risk budget across products.", likelyAsk: "What is the strongest way to express my event view?", actionTitle: "Cap aggregate worst-of exposure", actionBody: "Measure structured products by underlying and downside, then set a portfolio-level event-risk budget.", steps: ["Aggregate worst-of underlyings", "Define maximum loss budget", "Keep a liquid opportunity reserve"], avoidTitle: "Do not assess each structured note alone", avoidReason: "Several products can share the same worst-performing underlying and event path.", nextReview: "This month", clearance: "AMBER" },
  { slug: "yamamoto-kenji", id: "CL-0016", name: "Yamamoto Kenji", context: "Pre-retirement · pharmaceutical executive", source: "Executive compensation from a pharmaceutical group board role.", objectives: "Retire to Japan with JPY income, reduce employer-stock dependence, and support elderly parents.", aumM: 14.51, risk: "Balanced", base: "JPY", language: "Japanese", tax: "Japan", primaryRisk: "Currency", allocation: [{label:"Equity",value:67.7},{label:"Fixed Income",value:21.8},{label:"Cash and Equivalents",value:7.8},{label:"Commodities",value:2.6}], topName: "Kanto Pharma Holdings", topPct: 20.1, dailyPct: 100.0, cashPct: 7.8, nonBasePct: 56.4, gainM: 4.01, lossM: 0.05, needLabel: "JPY 18.0m annual parent support", needAmountM: 0.12, stance: "Emotionally attached to employer shares; the next dealing window is November 2026.", opening: "We do not need to sell the full holding. Let us agree a November plan before the window opens.", likelyAsk: "How can I reduce employer-stock risk without giving up the holding?", actionTitle: "Prepare the November dealing-window plan", actionBody: "Set a staged employer-stock reduction and direct proceeds to the future JPY income sleeve.", steps: ["Confirm dealing restrictions", "Agree a staged trim range", "Build JPY income for parent support"], avoidTitle: "Do not wait until the dealing window opens", avoidReason: "The emotional and compliance decisions should be agreed before execution is possible.", nextReview: "Before November", clearance: "AMBER" },
  { slug: "fong-enterprises-family-office", id: "CL-0017", name: "Fong Enterprises Family Office", context: "Multi-generational · G2 and G3", source: "Inherited wealth from the sale of a textiles and logistics group in 2009.", objectives: "Preserve capital across generations, fund education and venture allocations, and meet private-market commitments.", aumM: 87.90, risk: "Balanced", base: "USD", language: "English", tax: "Hong Kong SAR", primaryRisk: "Liquidity", allocation: [{label:"Alternatives",value:37.9},{label:"Equity",value:34.3},{label:"Fixed Income",value:18.3},{label:"Cash and Equivalents",value:6.1},{label:"Commodities",value:3.4}], topName: "Meridian Private Equity Fund VII", topPct: 13.7, dailyPct: 62.1, cashPct: 6.1, nonBasePct: 4.6, gainM: 19.29, lossM: 0.69, needLabel: "USD 16.7m commitments and education", needAmountM: 16.7, stance: "G2 wants a conservative core; G3 wants more technology and venture exposure.", opening: "The liquidity budget can define how much venture risk is available without forcing either generation to abandon its objective.", likelyAsk: "How much can G3 allocate to venture while all commitments remain funded?", actionTitle: "Set a family liquidity and risk budget", actionBody: "Reserve all confirmed commitments before allocating a separate G3 venture sleeve.", steps: ["Create a commitment calendar", "Exclude gated private credit from liquidity", "Set G2 core and G3 risk budgets"], avoidTitle: "Do not solve the governance dispute with one blended mandate", avoidReason: "Separate sleeves make the different objectives and accountabilities visible.", nextReview: "This week", clearance: "AMBER" },
  { slug: "elena-marchetti-wong", id: "CL-0018", name: "Elena Marchetti-Wong", context: "Peak earning years · luxury distributor", source: "Entrepreneurial wealth from luxury-goods distribution across Greater China.", objectives: "Hedge currency debasement and geopolitical risk, diversify from luxury retail, and plan Italian succession.", aumM: 22.60, risk: "Balanced", base: "EUR", language: "Italian", tax: "Italy", primaryRisk: "Concentration", allocation: [{label:"Equity",value:50.4},{label:"Fixed Income",value:23.0},{label:"Commodities",value:14.0},{label:"Cash and Equivalents",value:12.6}], topName: "Global Luxury and Consumer Brands Fund", topPct: 16.3, dailyPct: 100.0, cashPct: 12.6, nonBasePct: 46.8, gainM: 2.75, lossM: 0.39, needLabel: "EUR 0.85m succession costs", needAmountM: 0.93, stance: "Views gold as the only successful holding; business and largest equity fund share the luxury cycle.", opening: "Gold is doing its job, but both the hedge and luxury overlap now need explicit limits.", likelyAsk: "Should I keep the larger gold position while my business is under pressure?", actionTitle: "Rebalance the luxury-cycle overlap", actionBody: "Keep a defined gold hedge and reduce the portfolio exposure that moves with the operating business.", steps: ["Set the strategic gold range", "Measure business-plus-portfolio luxury exposure", "Reserve succession costs"], avoidTitle: "Do not treat the business and fund as separate risks", avoidReason: "Both depend on the same Greater China luxury cycle.", nextReview: "This month" },
  { slug: "abdullah-al-mansoori", id: "CL-0019", name: "Abdullah Al-Mansoori", context: "Peak earning years · Gulf logistics founder", source: "Entrepreneurial wealth from Gulf logistics, port services, and marine chartering.", objectives: "Build wealth outside the Gulf and shipping sectors, seed an Asian family office, and grow capital.", aumM: 32.21, risk: "Balanced Growth", base: "USD", language: "English", tax: "United Arab Emirates", primaryRisk: "Concentration", allocation: [{label:"Equity",value:58.0},{label:"Fixed Income",value:15.7},{label:"Structured Products",value:12.9},{label:"Cash and Equivalents",value:7.5},{label:"Alternatives",value:6.0}], topName: "Global Developed Equity Index Fund", topPct: 13.3, dailyPct: 81.1, cashPct: 7.5, nonBasePct: 24.3, gainM: 6.86, lossM: 0.52, needLabel: "USD 5.0m Asian family-office seed", needAmountM: 5.0, stance: "Asked how the portfolio changes if the Strait of Hormuz reopens and normalises.", opening: "We have modelled the reopening path and can use it to separate Gulf-linked risk from the family-office reserve.", likelyAsk: "What happens to my portfolio if the Strait reopens?", actionTitle: "Model and reduce Gulf overlap", actionBody: "Protect the family-office seed and review direct and structured exposures to energy and shipping normalisation.", steps: ["Ring-fence USD 5.0m", "Look through structured products", "Compare escalation and reopening scenarios"], avoidTitle: "Do not show only the escalation scenario", avoidReason: "The client specifically asked about normalisation and the portfolio may lose recent event gains.", nextReview: "This week" },
  { slug: "grace-adeyemi-lim", id: "CL-0020", name: "Grace Adeyemi-Lim", context: "Wealth accumulation · healthcare founder", source: "Entrepreneurial wealth from a private healthcare clinics group.", objectives: "Grow capital, establish a healthcare-access foundation, and buy Hong Kong property in 2027.", aumM: 19.06, risk: "Growth", base: "USD", language: "English", tax: "Hong Kong SAR", primaryRisk: "Liquidity", allocation: [{label:"Equity",value:75.1},{label:"Fixed Income",value:14.1},{label:"Alternatives",value:6.3},{label:"Cash and Equivalents",value:4.5}], topName: "Global Healthcare Equity Fund", topPct: 17.4, dailyPct: 93.7, cashPct: 4.5, nonBasePct: 11.9, gainM: 2.90, lossM: 0.05, needLabel: "USD 4.5m property and commitments", needAmountM: 4.5, stance: "Wants growth but recognises that her business and largest holdings share healthcare risk.", opening: "We can keep growth exposure while separating the 2027 property money and capping healthcare overlap.", likelyAsk: "How much healthcare exposure can I keep while funding the property purchase?", actionTitle: "Separate property funding from healthcare growth", actionBody: "Create the property reserve and set a combined business-plus-portfolio healthcare limit.", steps: ["Fund the 2027 property reserve", "Reserve private-market calls", "Measure healthcare overlap"], avoidTitle: "Do not fund the property from future market gains", avoidReason: "The payment date is fixed while equity returns are not.", nextReview: "This month", clearance: "AMBER" },
]

export const additionalClients: Record<string, ClientProfile> = Object.fromEntries(seeds.map((seed) => [seed.slug, profile(seed)]))
