import { recommendPortfolios, recommendationVersion, type RecommendationInput } from './recommendations'
import { snapshot, sum, type Wealth } from './wealth-model'
import { usd, type Evidence } from './calculation-evidence'

export function recommendationEvidence(wealth: Wealth, input: RecommendationInput, candidateId: string): Evidence {
  const report = recommendPortfolios(wealth, input), candidate = report.candidates.find(c => c.id === candidateId)
  if (!candidate) throw new Error('Unknown recommendation')
  const points = sum(candidate.scoreParts, part => part.points)
  return { title: `${candidate.name} · goal-fit calculation`, sourceDate: snapshot.asOf, diagram: 'recommendation',
    summary: candidate.scoreUnavailableReason || 'The score combines explicit goal coverage with a preference for smaller changes. Mandatory gates are tested separately.', result: candidate.score === null ? 'Score unavailable' : `${candidate.score.toFixed(2)} / 100 goal-fit points`, exact: candidate.score === null ? 'No score is invented for an unfunded option.' : `${candidate.score.toFixed(6)} points`,
    inputs: [{ label: 'Target account', value: input.accountId, source: 'Current RM selection; original mandate preserved', kind: 'RM input' }, { label: 'Goal priorities · 0 to 5', value: Object.entries(input.priorities).map(([key, value]) => `${key}: ${value}`).join('; '), source: 'Current draft priorities; confirm with the client', kind: 'RM input' }, { label: 'Reserve and income goals', value: `${usd(input.reserveGoal)} in ${input.reserveCurrency}; ${usd(input.annualNeed)} annual need`, source: 'RM inputs, in USD equivalents', kind: 'RM input' }, { label: 'Loss limit and horizon', value: `${input.lossLimit}% draft limit; ${input.horizon} years`, source: 'Current inputs; not evidence of agreed loss capacity', kind: 'RM input' }, { label: 'Simulated change', value: usd(candidate.amount), source: 'Eligible holdings only; ownership and sale restrictions retained', kind: 'Calculated' }],
    workings: [{ label: 'Goal weights', formula: 'Active goal weight = 90 × its priority ÷ sum of active priorities. Goals without a numeric target are excluded where required. The remaining 10 points reward a smaller change.' }, ...candidate.scoreParts.map(part => ({ label: part.label, formula: `${part.weight.toFixed(6)} weight × ${part.score.toFixed(6)} score ÷ 100 = ${part.points.toFixed(6)} points. ${part.reason}` })), { label: 'Total', formula: candidate.score === null ? candidate.scoreUnavailableReason! : `Sum unrounded component points = ${points.toFixed(6)} → ${candidate.score.toFixed(2)} / 100.` }],
    checks: [...candidate.gates.map(g => ({ label: g.label, status: (g.pass ? 'pass' : 'fail') as 'pass' | 'fail', detail: g.reason })), { label: 'Score reconciliation', status: candidate.score === null ? 'review' : Math.abs(points - candidate.score) < 1e-8 ? 'pass' : 'fail', detail: candidate.score === null ? 'An unavailable score must remain unavailable.' : 'Unrounded component points reconcile with the displayed model score.' }],
    reason: candidate.blocks.length ? `Not ranked for advice: ${candidate.blocks.map(g => g.reason).join(' ')}` : candidate.reasons.join(' '),
    limits: ['The score measures simulated goal fit, not model accuracy, return, suitability probability or investment success.', 'A good score cannot override a failed gate. Identical implemented portfolios can have identical scores.', ...candidate.tradeoffs],
    sources: [`recommendations.ts: ${recommendationVersion}`, `clients.csv: ${wealth.client.id}`, 'holdings.csv: current snapshot', 'mandates.csv: account bands and single-position limits', ...wealth.facilities.map(f => `credit_facilities.csv: ${f.id}`), ...wealth.client.notes.map(n => `rm_notes.json: ${n.id}`)],
  }
}
